version: '3.9'
services:
  backend:
    container_name: hermes-backend
    restart: always
    build:
      context: ./hermes-backend
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      DATABASE_HOST: hermes-db
      PORT: 8080
      GIN_MODE: release

  db:
    container_name: hermes-db
    image: postgres
    volumes:
      - ./sql/create.sql:/docker-entrypoint-initdb.d/create.sql
      - "postgres:/var/lib/postgresql/data"
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-root}
      POSTGRES_USER: ${DATABASE_USERNAME:-postgres}
      POSTGRES_DB: ${DATABASE_NAME:-hermes}
    ports:
      - ${DATABASE_PORT:-5432}:5432

  frontend:
    container_name: hermes-frontend
    build:
      context: hermes-frontend
      dockerfile: Dockerfile
    volumes:
      - 'react:/app'
      - '/app/node_modules'
    depends_on:
      - backend
    ports:
      - 3000:3000
    environment:
      PORT: 3000

volumes:
  react:
  postgres:
